FROM python:3.10
ENV PYTHONUNBUFFERED True

RUN pip install --upgrade pip
COPY ./requirements.txt /requirements.txt

RUN apt-get update && apt-get install -y python3-opencv
RUN pip install --no-cache-dir --upgrade -r /requirements.txt

COPY . .

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]